#!/usr/bin/env bash
# configures a new ubuntun server with custom Http header 
apt get -y update
apt get -y install nginx
ufw allow 'nginx HTTP'
echo 'Hello world!' > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
service nginx start
