#!/usr/bin/env bash
# configures a new ubuntun server with custom Http header 
apt-get -y update
apt-get -y install nginx
ufw allow 'nginx HTTP'
echo 'Hello world!' > /var/www/html/index.html
sed -i "52i\add_header X-Served-By $HOSTNAME always;" /etc/nginx/sites-enabled/default
service nginx start
