#!/usr/bin/env bash
# install and setup haprroxy on a new ubuntu machine 

apt-get update
apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy

echo "
	listen load_balancer
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 26340-web-01 34.238.194.225 check
	server 26340-web-02 3.235.224.130 check
	option httpchk
  " >> /etc/haproxy/haproxy.cfg

service haproxy start 
